dataset:
  name: "MNIST"
  mnist:
    root: "Data"
    train: true
    download: true
    batch_size: 128
    shuffle: true
    transform:
      - type: "ToTensor"
      - type: "Normalize"
        mean: [0.5]
        std: [0.5]